### ISSUE TITLE
Recommended default MTU

### ISSUE THREAD

**Issue by heiher** [SaeedDev94/Xray#25]
For better transmission performance, I recommended setting the default MTU value to 8500.

**Comment by SaeedDev94** [comment]
@heiher Thanks for your suggestion  
I set default MTU value to 1500 because it's the default value for most of modems and routers  
Also user can customize MTU value in advanced settings  
Isn't lower MTU value better for slow internet speed connections ?  
Personally my internet speed is really slow, sometimes it's less than 800 K bit per second (less than 100 K byte per second) !!! ☹️  
BTW I don't know much about MTU, If you still think 8500 is better even for really slow connections I'll do it ❤️

**Comment by heiher** [comment]
> @heiher Thanks for your suggestion I set default MTU value to 1500 because it's the default value for most of modems and routers Also user can customize MTU value in advanced settings Isn't lower MTU value better for slow internet speed connections ? Personally my internet speed is really slow, sometimes it's less than 800 K bit per second (less than 100 K byte per second) !!! ☹️ BTW I don't know much about MTU, If you still think 8500 is better even for really slow connections I'll do it ❤️

In tun2socks mode, the MTU is only used for the IP stack of the virtual network card and the operating system, and has nothing to do with the modem and router in the upstream link.

**Comment by SaeedDev94** [comment]
> In tun2socks mode, the MTU is only used for the IP stack of the virtual network card and the operating system, and has nothing to do with the modem and router in the upstream link.

And what about slow connections ? (higher or lower value for MTU)

**Comment by heiher** [comment]
> > In tun2socks mode, the MTU is only used for the IP stack of the virtual network card and the operating system, and has nothing to do with the modem and router in the upstream link.
> 
> And what about slow connections ? (higher or lower value for MTU)

Higher MTU is also good for slow networks.

**Comment by SaeedDev94** [comment]
> Higher MTU is also good for slow networks.
So I'll do it (next update) for sure, thanks again ❤️

**Comment by SaeedDev94** [comment]
https://github.com/SaeedDev94/Xray/commit/0576831627e9a576a01fd11a142718286299d610
